type: ModularModel1
key_size: 64
value_size: 64
num_heads: 4
input_modules:
  "obs":
    type: LinearInput
    kwargs:
      input_size:
        source: 'observation_space'
        accessor: '["obs"].shape[0]'
  reward:
    type: ScalarInput
    weight_config:
      freeze: true
      key_prefix: 'input_modules.input_modules.reward'
      filename: ''
  done:
    type: IgnoredInput
  action:
    type: LinearInput
    kwargs:
      input_size:
        source: 'action_space'
        accessor: '.shape[0]'
output_modules:
  value:
    type: LinearOutput
    kwargs:
      dynamic_query: true
      output_size: 1
  action_mean:
    type: LinearOutput
    kwargs:
      dynamic_query: true
      output_size:
        source: 'action_space'
        accessor: '.shape[0]'
  action_logstd:
    type: LinearOutput
    kwargs:
      dynamic_query: true
      output_size:
        source: 'action_space'
        accessor: '.shape[0]'
core_modules:
  type: AttentionLSTM
  kwargs:
    hidden_size: 64
    dynamic_query: true
  weight_config:
    freeze: true
    key_prefix: 'core_modules.0'
    filename: ''
