- type: AsyncVectorEnv # AsyncVectorEnv, SyncVectorEnv, or Env
  envs:
  - name: Reacher
    kwargs: # Arguments for gymnasium.make
      id: ReacherNoLimit-v4
    repeat: 8
    wrappers:
    - type: TimeLimit
      kwargs:
        max_episode_steps: 1000
    - type: PadObservation
      kwargs:
        shape: [376]
    - type: PadAction
      kwargs:
        shape: [17]
    - type: MujocoTaskRewardWrapper
      kwargs:
        task_reward_key: reward_dist
        control_cost_key: reward_ctrl
        total_energy: 100
    - type: MetaWrapper
      kwargs:
        episode_stack: 1
        dict_obs: true
        randomize: false
    - type: ClipAction
