- type: AsyncVectorEnv # AsyncVectorEnv, SyncVectorEnv, or Env
  model_name: fw
  train_enabled: true
  envs:
  - kwargs: # Arguments for gymnasium.make
      id: HalfCheetahNoVelocityForward-v4
    name: forward
    repeat: 8
    wrappers:
    - type: TimeLimit
      kwargs:
        max_episode_steps: 1000
    - type: MetaWrapper
      kwargs:
        episode_stack: 1
        dict_obs: true
        randomize: false
    - type: ClipAction
- type: AsyncVectorEnv # AsyncVectorEnv, SyncVectorEnv, or Env
  model_name: bw
  train_enabled: true
  envs:
  - kwargs: # Arguments for gymnasium.make
      id: HalfCheetahNoVelocityBackward-v4
    name: backward
    repeat: 8
    wrappers:
    - type: TimeLimit
      kwargs:
        max_episode_steps: 1000
    - type: MetaWrapper
      kwargs:
        episode_stack: 1
        dict_obs: true
        randomize: false
    - type: ClipAction
- type: AsyncVectorEnv # AsyncVectorEnv, SyncVectorEnv, or Env
  model_name: fwbw
  train_enabled: false
  envs:
  - kwargs: # Arguments for gymnasium.make
      id: HalfCheetahNoVelocityForward-v4
    name: forward
    repeat: 8
    wrappers:
    - type: TimeLimit
      kwargs:
        max_episode_steps: 1000
    - type: MetaWrapper
      kwargs:
        episode_stack: 1
        dict_obs: true
        randomize: false
    - type: ClipAction
  - kwargs: # Arguments for gymnasium.make
      id: HalfCheetahNoVelocityBackward-v4
    name: backward
    repeat: 8
    wrappers:
    - type: TimeLimit
      kwargs:
        max_episode_steps: 1000
    - type: MetaWrapper
      kwargs:
        episode_stack: 1
        dict_obs: true
        randomize: false
    - type: ClipAction
