- type: AsyncVectorEnv # AsyncVectorEnv, SyncVectorEnv, or Env
  envs:
  - kwargs: # Arguments for gymnasium.make
      id: HalfCheetahNoVelocityForward-v4
    repeat: 8
    wrappers:
    - type: TimeLimit
      kwargs:
        max_episode_steps: 1000
    - type: MetaWrapper
      kwargs:
        episode_stack: 1
        dict_obs: true
        randomize: false
    - type: ClipAction
  - kwargs: # Arguments for gymnasium.make
      id: HalfCheetahNoVelocityBackward-v4
    repeat: 8
    wrappers:
    - type: TimeLimit
      kwargs:
        max_episode_steps: 1000
    - type: MetaWrapper
      kwargs:
        episode_stack: 1
        dict_obs: true
        randomize: false
    - type: ClipAction
